Repository PlayPickUp/pickup-ui, pull requests merged in 2022-01, with the labels that each got.

#273 Next
  packages/core/src/ThemeProvider/defaultTheme.ts
  packages/core/src/types/index.ts
  playground/src/App/index.tsx
Labels: release

#283 feat(nested input): shrunk padding on submit button
  packages/core/src/NestedInput/index.tsx
Labels: enhancement ✨

#285 fix(icons): set maxwidth to match size
  packages/core/src/Icon/index.tsx
Labels: bug 🐛

#286 Release 1/28/22
  packages/core/src/Icon/index.tsx
  packages/core/src/NestedInput/index.tsx
  packages/core/src/Paper/Paper.test.tsx
  packages/core/src/Paper/__snapshots__/Paper.test.tsx.snap
  packages/core/src/Paper/index.tsx
  packages/core/src/ThemeProvider/GlobalsAndReset.tsx
  playground/src/App/index.tsx
Labels: release
